name: classeval
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy<2.0
  - pandas
  - scipy
  - pillow
  - pyyaml
  - requests
  - openai
  - cython
  - nltk
  - jsonlines
  - regex
  - reportlab
  - setuptools
  - wheel
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.11.2
      - bs4==0.0.2
      - cachetools==5.5.2
      - certifi
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - dotenv==0.9.9
      - et-xmlfile==2.0.0
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec
      - func-timeout==4.3.5
      - gensim==4.2.0
      - google-ai-generativelanguage==0.1.0
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - google-generativeai==0.1.0rc1
      - googleapis-common-protos==1.72.0
      - grpcio==1.70.0
      - grpcio-status==1.62.3
      - huggingface-hub==0.36.0
      - idna==3.11
      - joblib==1.4.2
      - levenshtein==0.20.9
      - multidict==6.1.0
      - openpyxl==3.0.10
      - packaging==25.0
      - propcache==0.2.0
      - proto-plus==1.26.1
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pypdf2==3.0.1
      - python-dateutil==2.9.0
      - python-dotenv==1.0.1
      - pytz
      - rapidfuzz==2.15.2
      - rsa==4.9.1
      - safetensors==0.5.3
      - smart-open==7.3.1
      - soupsieve==2.7
      - tokenizers==0.20.3
      - tqdm==4.65.2
      - uv==0.9.14
      - wrapt==2.0.1
      - yarl==1.15.2
      - torch==2.1.2
      - torchvision==0.16.2
      - transformers==4.46.0
      - accelerate==0.26.0
