name: classeval
channels:
  - defaults
dependencies:
  - ca-certificates=2025.11.4=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.18=h543e019_0
  - pip=24.2=py38haa95532_0
  - python=3.8.20=h8205438_0
  - sqlite=3.51.0=hda9a48d_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.11.2
      - bs4==0.0.2
      - cachetools==5.5.2
      - certifi==2025.11.12
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - cython==0.29.28
      - dotenv==0.9.9
      - et-xmlfile==2.0.0
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - func-timeout==4.3.5
      - gensim==4.2.0
      - google-ai-generativelanguage==0.1.0
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - google-generativeai==0.1.0rc1
      - googleapis-common-protos==1.72.0
      - grpcio==1.70.0
      - grpcio-status==1.62.3
      - huggingface-hub==0.36.0
      - idna==3.11
      - joblib==1.4.2
      - jsonlines==3.1.0
      - levenshtein==0.20.9
      - multidict==6.1.0
      - nltk==3.9.1
      - numpy==1.22.4
      - openai==0.27.10
      - openpyxl==3.0.10
      - packaging==25.0
      - pandas==1.4.4
      - pillow==9.1.1
      - propcache==0.2.0
      - proto-plus==1.26.1
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pypdf2==3.0.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - rapidfuzz==2.15.2
      - regex==2024.11.6
      - reportlab==4.0.9
      - requests==2.32.4
      - rsa==4.9.1
      - safetensors==0.5.3
      - scipy==1.8.1
      - setuptools==68.0.0
      - six==1.17.0
      - smart-open==7.3.1
      - soupsieve==2.7
      - tokenizers==0.20.3
      - torch==1.10.2
      - tqdm==4.65.2
      - transformers==4.46.3
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - uv==0.9.14
      - wrapt==2.0.1
      - yarl==1.15.2
prefix: D:\Anaconda\envs\classeval
